service: ted-blog
image: etmartinkazoo/ted-blog

servers:
  web:
    - 161.35.12.128

builder:
  arch:
    - amd64
  remote: ssh://root@178.156.154.90:22
  local: false

proxy:
  ssl: true
  host: tedmartin.us
  app_port: 3000

registry:
  username: etmartinkazoo

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "storage:/rails/storage"

asset_path: /rails/public/assets
